server:
  port: 8162
spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100

exceptionmanager:
  connection:
    scheme: http

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

queueconfig:
  sms-confirmation-topic: rm-internal-sms-confirmation
  sms-request-enriched-topic: rm-internal-sms-request-enriched
  sms-request-subscription: rm-internal-sms-request_notify-service
  sms-request-enriched-subscription: rm-internal-sms-request-enriched_notify-service
  email-confirmation-topic: rm-internal-email-confirmation
  email-request-enriched-topic: rm-internal-email-request-enriched
  email-request-subscription: rm-internal-email-request_notify-service
  email-request-enriched-subscription: rm-internal-email-request-enriched_notify-service


management:
  endpoints:
    access:
      default: none
  endpoint:
    health:
      access: READ_ONLY
  health:
    pubsub:
      enabled: false
  metrics:
    tags:
      application: Notify Service
      pod: ${HOSTNAME}
  stackdriver:
    metrics:
      export:
        enabled: false
        project-id: dummy-project-id
        step: PT1M

messagelogging:
  logstacktraces: false

sms-request-enriched-delay: 50  # milliseconds
email-request-enriched-delay: 50  # milliseconds

logging:
  profile: DEV
  level:
    root: INFO # NB: This must never be set to a lower level than INFO as it can leak data into logs
    com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter: ERROR
    uk.gov.ons.ssdc.notifysvc.messaging.EmailRequestEnrichedReceiver: DEBUG # To show our debug timing logs
    uk.gov.ons.ssdc.notifysvc.messaging.EmailRequestReceiver: DEBUG # To show our debug timing logs
