server:
  port: 9999

info:
  app:
    name: Support Tool
    version: 1.0

spring:
  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      enabled: true
#     If these values change then you must update the max_file_size_in_mb in SampleUpload.js
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:6432/rm?readOnly=true
    username: appuser
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 500
          order_inserts: true
          lob:
            non_contextual_creation: true
  task:
    scheduling:
      pool:
        size: 10

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  profile: DEV
  level:
    root: INFO

management:
  endpoints:
    access:
      default: none
  endpoint:
    health:
      access: READ_ONLY
  health:
    pubsub:
      enabled: false
  metrics:
    tags:
      application: Support Tool
      pod: ${HOSTNAME}
  stackdriver:
    metrics:
      export:
        project-id: dummy-project-id
        enabled: false
        step: PT1M

notifyservice:
  connection:
    scheme: http
    host: localhost
    port: 8162

iapaudience: DUMMY

iap-enforced: true # This ** MUST ALWAYS!! ** be true in production!!!
dummyuseridentity: dummy@fake-email.com
dummysuperuseridentity: dummy@fake-email.com

exportfiledestinationconfigfile: dummy-export-file-destination-config.json
notifyserviceconfigfile: dummy-notify-config.json
queueconfig:
  new-case-topic: event_new-case
  print-fulfilment-topic: event_print-fulfilment
  deactivate-uac-topic: event_deactivate-uac
  refusal-event-topic: event_refusal
  invalid-case-event-topic: event_invalid-case
  update-sample-topic: event_update-sample
  update-sample-sensitive-topic: event_update-sample-sensitive
  survey-update-event-topic: event_survey-update
  collection-exercise-update-event-topic: event_collection-exercise-update
  publishtimeout: 30  # In seconds

file-upload-storage-path: /tmp/

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666
  exceptioncountthreshold: 50


CSP-upgrade-policy: "upgrade-insecure-requests;"
